/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * PlanejAI API
 * API para o projeto acadêmico PlanejAI
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from "../../fetch";
export type GetNumberOfCompletedDays200 = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  numberOfDays: number;
};

export type GetNumberOfCompletedDays401 = {
  error: string;
  code: string;
};

export type GetNumberOfCompletedDays500 = {
  error: string;
  code: string;
};

export type CreateWeeklyPlanBodyDailyPlansItemDay =
  (typeof CreateWeeklyPlanBodyDailyPlansItemDay)[keyof typeof CreateWeeklyPlanBodyDailyPlansItemDay];

export const CreateWeeklyPlanBodyDailyPlansItemDay = {
  SUNDAY: "SUNDAY",
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
} as const;

export type CreateWeeklyPlanBodyDailyPlansItemTasksItem = {
  /** @minLength 1 */
  title: string;
  isCompleted?: boolean;
  /** @minimum 1 */
  expectedDurationTimeInSeconds: number;
};

export type CreateWeeklyPlanBodyDailyPlansItem = {
  day: CreateWeeklyPlanBodyDailyPlansItemDay;
  isRest?: boolean;
  tasks: CreateWeeklyPlanBodyDailyPlansItemTasksItem[];
};

export type CreateWeeklyPlanBody = {
  /** @minLength 1 */
  title: string;
  dailyPlans: CreateWeeklyPlanBodyDailyPlansItem[];
};

export type CreateWeeklyPlan201DailyPlansItemDay =
  (typeof CreateWeeklyPlan201DailyPlansItemDay)[keyof typeof CreateWeeklyPlan201DailyPlansItemDay];

export const CreateWeeklyPlan201DailyPlansItemDay = {
  SUNDAY: "SUNDAY",
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
} as const;

export type CreateWeeklyPlan201DailyPlansItemTasksItem = {
  /** @minLength 1 */
  title: string;
  isCompleted: boolean;
  /** @minimum 1 */
  expectedDurationTimeInSeconds: number;
};

export type CreateWeeklyPlan201DailyPlansItem = {
  day: CreateWeeklyPlan201DailyPlansItemDay;
  isRest: boolean;
  tasks: CreateWeeklyPlan201DailyPlansItemTasksItem[];
};

export type CreateWeeklyPlan201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  title: string;
  dailyPlans: CreateWeeklyPlan201DailyPlansItem[];
};

export type CreateWeeklyPlan400 = {
  error: string;
  code: string;
};

export type CreateWeeklyPlan401 = {
  error: string;
  code: string;
};

export type CreateWeeklyPlan404 = {
  error: string;
  code: string;
};

export type CreateWeeklyPlan500 = {
  error: string;
  code: string;
};

export type StartPlanningSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  planningSessionId: string;
};

export type StartPlanningSession401 = {
  error: string;
  code: string;
};

export type StartPlanningSession404 = {
  error: string;
  code: string;
};

export type StartPlanningSession409 = {
  error: string;
  code: string;
};

export type StartPlanningSession422 = {
  error: string;
  code: string;
};

export type StartPlanningSession500 = {
  error: string;
  code: string;
};

export type CompletePlanningSessionBody = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
};

export type CompletePlanningSession200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  startedAt: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
};

export type CompletePlanningSession401 = {
  error: string;
  code: string;
};

export type CompletePlanningSession404 = {
  error: string;
  code: string;
};

export type CompletePlanningSession500 = {
  error: string;
  code: string;
};

export type GetWeeklyPlan200DailyPlansItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  weekDay: string;
  isRest: boolean;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  estimatedDurationInSeconds: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  tasksCount: number;
};

export type GetWeeklyPlan200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  dailyPlans: GetWeeklyPlan200DailyPlansItem[];
};

export type GetWeeklyPlan401 = {
  error: string;
  code: string;
};

export type GetWeeklyPlan404 = {
  error: string;
  code: string;
};

export type GetWeeklyPlan500 = {
  error: string;
  code: string;
};

export type GetDailyPlan200TasksItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  title: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  dailyPlanId: string;
  isCompleted: boolean;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  expectedDurationTimeInSeconds: number;
};

export type GetDailyPlan200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  title: string;
  isRest: boolean;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  estimatedDurationInSeconds: number;
  weekDay: string;
  tasks: GetDailyPlan200TasksItem[];
};

export type GetDailyPlan401 = {
  error: string;
  code: string;
};

export type GetDailyPlan404 = {
  error: string;
  code: string;
};

export type GetDailyPlan500 = {
  error: string;
  code: string;
};

export type CompleteAllDailyPlanTask200TasksItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  isCompleted: boolean;
};

export type CompleteAllDailyPlanTask200 = {
  tasks: CompleteAllDailyPlanTask200TasksItem[];
};

export type CompleteAllDailyPlanTask401 = {
  error: string;
  code: string;
};

export type CompleteAllDailyPlanTask404 = {
  error: string;
  code: string;
};

export type CompleteAllDailyPlanTask500 = {
  error: string;
  code: string;
};

export type GetHomeData200TodayPlanningCompletedTasksItem = {
  title: string;
};

export type GetHomeData200TodayPlanningUncompletedTasksItem = {
  title: string;
};

export type GetHomeData200TodayPlanning = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  planningId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  weekDay: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  tasksCount: number;
  completedTasks: GetHomeData200TodayPlanningCompletedTasksItem[];
  uncompletedTasks: GetHomeData200TodayPlanningUncompletedTasksItem[];
};

export type GetHomeData200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  activePlanningDayId: string;
  todayPlanning: GetHomeData200TodayPlanning;
};

export type GetHomeData401 = {
  error: string;
  code: string;
};

export type GetHomeData404 = {
  error: string;
  code: string;
};

export type GetHomeData500 = {
  error: string;
  code: string;
};

export type CompleteTask200Task = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  isCompleted: boolean;
};

export type CompleteTask200 = {
  task: CompleteTask200Task;
};

export type CompleteTask401 = {
  error: string;
  code: string;
};

export type CompleteTask404 = {
  error: string;
  code: string;
};

export type CompleteTask500 = {
  error: string;
  code: string;
};

export type UncompleteTask200Task = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  isCompleted: boolean;
};

export type UncompleteTask200 = {
  task: UncompleteTask200Task;
};

export type UncompleteTask401 = {
  error: string;
  code: string;
};

export type UncompleteTask404 = {
  error: string;
  code: string;
};

export type UncompleteTask500 = {
  error: string;
  code: string;
};

export type PostAiBody = {
  messages: unknown[];
};

/**
 * @nullable
 */
export type GetMe200 = {
  userId: string;
  userName: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  reasonForProcrastination: number;
} | null;

export type GetMe401 = {
  error: string;
  code: string;
};

export type GetMe500 = {
  error: string;
  code: string;
};

export type ListReasonsForProcrastination200Item = {
  reasonId: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  reasonNumber: number;
  reasonText: string;
};

export type ListReasonsForProcrastination401 = {
  error: string;
  code: string;
};

export type ListReasonsForProcrastination500 = {
  error: string;
  code: string;
};

export type Get200 = {
  message: string;
};

/**
 * @summary Get the number of days where all tasks were completed
 */
export type getNumberOfCompletedDaysResponse200 = {
  data: GetNumberOfCompletedDays200;
  status: 200;
};

export type getNumberOfCompletedDaysResponse401 = {
  data: GetNumberOfCompletedDays401;
  status: 401;
};

export type getNumberOfCompletedDaysResponse500 = {
  data: GetNumberOfCompletedDays500;
  status: 500;
};

export type getNumberOfCompletedDaysResponseSuccess =
  getNumberOfCompletedDaysResponse200 & {
    headers: Headers;
  };
export type getNumberOfCompletedDaysResponseError = (
  | getNumberOfCompletedDaysResponse401
  | getNumberOfCompletedDaysResponse500
) & {
  headers: Headers;
};

export type getNumberOfCompletedDaysResponse =
  | getNumberOfCompletedDaysResponseSuccess
  | getNumberOfCompletedDaysResponseError;

export const getGetNumberOfCompletedDaysUrl = () => {
  return `/weekly-plans/days/number-of-completed-tasks`;
};

export const getNumberOfCompletedDays = async (
  options?: RequestInit,
): Promise<getNumberOfCompletedDaysResponse> => {
  return customFetch<getNumberOfCompletedDaysResponse>(
    getGetNumberOfCompletedDaysUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export type createWeeklyPlanResponse201 = {
  data: CreateWeeklyPlan201;
  status: 201;
};

export type createWeeklyPlanResponse400 = {
  data: CreateWeeklyPlan400;
  status: 400;
};

export type createWeeklyPlanResponse401 = {
  data: CreateWeeklyPlan401;
  status: 401;
};

export type createWeeklyPlanResponse404 = {
  data: CreateWeeklyPlan404;
  status: 404;
};

export type createWeeklyPlanResponse500 = {
  data: CreateWeeklyPlan500;
  status: 500;
};

export type createWeeklyPlanResponseSuccess = createWeeklyPlanResponse201 & {
  headers: Headers;
};
export type createWeeklyPlanResponseError = (
  | createWeeklyPlanResponse400
  | createWeeklyPlanResponse401
  | createWeeklyPlanResponse404
  | createWeeklyPlanResponse500
) & {
  headers: Headers;
};

export type createWeeklyPlanResponse =
  | createWeeklyPlanResponseSuccess
  | createWeeklyPlanResponseError;

export const getCreateWeeklyPlanUrl = () => {
  return `/weekly-plans/`;
};

export const createWeeklyPlan = async (
  createWeeklyPlanBody: CreateWeeklyPlanBody,
  options?: RequestInit,
): Promise<createWeeklyPlanResponse> => {
  return customFetch<createWeeklyPlanResponse>(getCreateWeeklyPlanUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createWeeklyPlanBody),
  });
};

/**
 * @summary Start a planning session for a specific daily plan
 */
export type startPlanningSessionResponse201 = {
  data: StartPlanningSession201;
  status: 201;
};

export type startPlanningSessionResponse401 = {
  data: StartPlanningSession401;
  status: 401;
};

export type startPlanningSessionResponse404 = {
  data: StartPlanningSession404;
  status: 404;
};

export type startPlanningSessionResponse409 = {
  data: StartPlanningSession409;
  status: 409;
};

export type startPlanningSessionResponse422 = {
  data: StartPlanningSession422;
  status: 422;
};

export type startPlanningSessionResponse500 = {
  data: StartPlanningSession500;
  status: 500;
};

export type startPlanningSessionResponseSuccess =
  startPlanningSessionResponse201 & {
    headers: Headers;
  };
export type startPlanningSessionResponseError = (
  | startPlanningSessionResponse401
  | startPlanningSessionResponse404
  | startPlanningSessionResponse409
  | startPlanningSessionResponse422
  | startPlanningSessionResponse500
) & {
  headers: Headers;
};

export type startPlanningSessionResponse =
  | startPlanningSessionResponseSuccess
  | startPlanningSessionResponseError;

export const getStartPlanningSessionUrl = (
  weeklyPlanId: string,
  dailyPlanId: string,
) => {
  return `/weekly-plans/${weeklyPlanId}/days/${dailyPlanId}/sessions`;
};

export const startPlanningSession = async (
  weeklyPlanId: string,
  dailyPlanId: string,
  options?: RequestInit,
): Promise<startPlanningSessionResponse> => {
  return customFetch<startPlanningSessionResponse>(
    getStartPlanningSessionUrl(weeklyPlanId, dailyPlanId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Complete a planning session
 */
export type completePlanningSessionResponse200 = {
  data: CompletePlanningSession200;
  status: 200;
};

export type completePlanningSessionResponse401 = {
  data: CompletePlanningSession401;
  status: 401;
};

export type completePlanningSessionResponse404 = {
  data: CompletePlanningSession404;
  status: 404;
};

export type completePlanningSessionResponse500 = {
  data: CompletePlanningSession500;
  status: 500;
};

export type completePlanningSessionResponseSuccess =
  completePlanningSessionResponse200 & {
    headers: Headers;
  };
export type completePlanningSessionResponseError = (
  | completePlanningSessionResponse401
  | completePlanningSessionResponse404
  | completePlanningSessionResponse500
) & {
  headers: Headers;
};

export type completePlanningSessionResponse =
  | completePlanningSessionResponseSuccess
  | completePlanningSessionResponseError;

export const getCompletePlanningSessionUrl = (
  weeklyPlanId: string,
  dailyPlanId: string,
  sessionId: string,
) => {
  return `/weekly-plans/${weeklyPlanId}/days/${dailyPlanId}/sessions/${sessionId}`;
};

export const completePlanningSession = async (
  weeklyPlanId: string,
  dailyPlanId: string,
  sessionId: string,
  completePlanningSessionBody: CompletePlanningSessionBody,
  options?: RequestInit,
): Promise<completePlanningSessionResponse> => {
  return customFetch<completePlanningSessionResponse>(
    getCompletePlanningSessionUrl(weeklyPlanId, dailyPlanId, sessionId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(completePlanningSessionBody),
    },
  );
};

/**
 * @summary Get a weekly plan with its daily plans summary
 */
export type getWeeklyPlanResponse200 = {
  data: GetWeeklyPlan200;
  status: 200;
};

export type getWeeklyPlanResponse401 = {
  data: GetWeeklyPlan401;
  status: 401;
};

export type getWeeklyPlanResponse404 = {
  data: GetWeeklyPlan404;
  status: 404;
};

export type getWeeklyPlanResponse500 = {
  data: GetWeeklyPlan500;
  status: 500;
};

export type getWeeklyPlanResponseSuccess = getWeeklyPlanResponse200 & {
  headers: Headers;
};
export type getWeeklyPlanResponseError = (
  | getWeeklyPlanResponse401
  | getWeeklyPlanResponse404
  | getWeeklyPlanResponse500
) & {
  headers: Headers;
};

export type getWeeklyPlanResponse =
  | getWeeklyPlanResponseSuccess
  | getWeeklyPlanResponseError;

export const getGetWeeklyPlanUrl = (id: string) => {
  return `/weekly-plans/${id}`;
};

export const getWeeklyPlan = async (
  id: string,
  options?: RequestInit,
): Promise<getWeeklyPlanResponse> => {
  return customFetch<getWeeklyPlanResponse>(getGetWeeklyPlanUrl(id), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get a daily plan with its tasks
 */
export type getDailyPlanResponse200 = {
  data: GetDailyPlan200;
  status: 200;
};

export type getDailyPlanResponse401 = {
  data: GetDailyPlan401;
  status: 401;
};

export type getDailyPlanResponse404 = {
  data: GetDailyPlan404;
  status: 404;
};

export type getDailyPlanResponse500 = {
  data: GetDailyPlan500;
  status: 500;
};

export type getDailyPlanResponseSuccess = getDailyPlanResponse200 & {
  headers: Headers;
};
export type getDailyPlanResponseError = (
  | getDailyPlanResponse401
  | getDailyPlanResponse404
  | getDailyPlanResponse500
) & {
  headers: Headers;
};

export type getDailyPlanResponse =
  | getDailyPlanResponseSuccess
  | getDailyPlanResponseError;

export const getGetDailyPlanUrl = (
  weeklyPlanId: string,
  dailyPlanId: string,
) => {
  return `/weekly-plans/${weeklyPlanId}/days/${dailyPlanId}`;
};

export const getDailyPlan = async (
  weeklyPlanId: string,
  dailyPlanId: string,
  options?: RequestInit,
): Promise<getDailyPlanResponse> => {
  return customFetch<getDailyPlanResponse>(
    getGetDailyPlanUrl(weeklyPlanId, dailyPlanId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Mark all tasks in a daily plan as completed
 */
export type completeAllDailyPlanTaskResponse200 = {
  data: CompleteAllDailyPlanTask200;
  status: 200;
};

export type completeAllDailyPlanTaskResponse401 = {
  data: CompleteAllDailyPlanTask401;
  status: 401;
};

export type completeAllDailyPlanTaskResponse404 = {
  data: CompleteAllDailyPlanTask404;
  status: 404;
};

export type completeAllDailyPlanTaskResponse500 = {
  data: CompleteAllDailyPlanTask500;
  status: 500;
};

export type completeAllDailyPlanTaskResponseSuccess =
  completeAllDailyPlanTaskResponse200 & {
    headers: Headers;
  };
export type completeAllDailyPlanTaskResponseError = (
  | completeAllDailyPlanTaskResponse401
  | completeAllDailyPlanTaskResponse404
  | completeAllDailyPlanTaskResponse500
) & {
  headers: Headers;
};

export type completeAllDailyPlanTaskResponse =
  | completeAllDailyPlanTaskResponseSuccess
  | completeAllDailyPlanTaskResponseError;

export const getCompleteAllDailyPlanTaskUrl = (id: string) => {
  return `/daily-plan/complete-all-task/${id}`;
};

export const completeAllDailyPlanTask = async (
  id: string,
  options?: RequestInit,
): Promise<completeAllDailyPlanTaskResponse> => {
  return customFetch<completeAllDailyPlanTaskResponse>(
    getCompleteAllDailyPlanTaskUrl(id),
    {
      ...options,
      method: "PATCH",
    },
  );
};

/**
 * @summary Get home page data for a given date
 */
export type getHomeDataResponse200 = {
  data: GetHomeData200;
  status: 200;
};

export type getHomeDataResponse401 = {
  data: GetHomeData401;
  status: 401;
};

export type getHomeDataResponse404 = {
  data: GetHomeData404;
  status: 404;
};

export type getHomeDataResponse500 = {
  data: GetHomeData500;
  status: 500;
};

export type getHomeDataResponseSuccess = getHomeDataResponse200 & {
  headers: Headers;
};
export type getHomeDataResponseError = (
  | getHomeDataResponse401
  | getHomeDataResponse404
  | getHomeDataResponse500
) & {
  headers: Headers;
};

export type getHomeDataResponse =
  | getHomeDataResponseSuccess
  | getHomeDataResponseError;

export const getGetHomeDataUrl = (date: string) => {
  return `/home/${date}`;
};

export const getHomeData = async (
  date: string,
  options?: RequestInit,
): Promise<getHomeDataResponse> => {
  return customFetch<getHomeDataResponse>(getGetHomeDataUrl(date), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Mark a task as completed
 */
export type completeTaskResponse200 = {
  data: CompleteTask200;
  status: 200;
};

export type completeTaskResponse401 = {
  data: CompleteTask401;
  status: 401;
};

export type completeTaskResponse404 = {
  data: CompleteTask404;
  status: 404;
};

export type completeTaskResponse500 = {
  data: CompleteTask500;
  status: 500;
};

export type completeTaskResponseSuccess = completeTaskResponse200 & {
  headers: Headers;
};
export type completeTaskResponseError = (
  | completeTaskResponse401
  | completeTaskResponse404
  | completeTaskResponse500
) & {
  headers: Headers;
};

export type completeTaskResponse =
  | completeTaskResponseSuccess
  | completeTaskResponseError;

export const getCompleteTaskUrl = (id: string) => {
  return `/tasks/complete-task/${id}`;
};

export const completeTask = async (
  id: string,
  options?: RequestInit,
): Promise<completeTaskResponse> => {
  return customFetch<completeTaskResponse>(getCompleteTaskUrl(id), {
    ...options,
    method: "PATCH",
  });
};

/**
 * @summary Mark a task as incomplete
 */
export type uncompleteTaskResponse200 = {
  data: UncompleteTask200;
  status: 200;
};

export type uncompleteTaskResponse401 = {
  data: UncompleteTask401;
  status: 401;
};

export type uncompleteTaskResponse404 = {
  data: UncompleteTask404;
  status: 404;
};

export type uncompleteTaskResponse500 = {
  data: UncompleteTask500;
  status: 500;
};

export type uncompleteTaskResponseSuccess = uncompleteTaskResponse200 & {
  headers: Headers;
};
export type uncompleteTaskResponseError = (
  | uncompleteTaskResponse401
  | uncompleteTaskResponse404
  | uncompleteTaskResponse500
) & {
  headers: Headers;
};

export type uncompleteTaskResponse =
  | uncompleteTaskResponseSuccess
  | uncompleteTaskResponseError;

export const getUncompleteTaskUrl = (id: string) => {
  return `/tasks/uncomplete-task/${id}`;
};

export const uncompleteTask = async (
  id: string,
  options?: RequestInit,
): Promise<uncompleteTaskResponse> => {
  return customFetch<uncompleteTaskResponse>(getUncompleteTaskUrl(id), {
    ...options,
    method: "PATCH",
  });
};

/**
 * @summary Send messages to the AI planning assistant
 */
export type postAiResponse200 = {
  data: void;
  status: 200;
};

export type postAiResponseSuccess = postAiResponse200 & {
  headers: Headers;
};
export type postAiResponse = postAiResponseSuccess;

export const getPostAiUrl = () => {
  return `/ai/`;
};

export const postAi = async (
  postAiBody: PostAiBody,
  options?: RequestInit,
): Promise<postAiResponse> => {
  return customFetch<postAiResponse>(getPostAiUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postAiBody),
  });
};

/**
 * @summary Get current user reason for procrastination data
 */
export type getMeResponse200 = {
  data: GetMe200;
  status: 200;
};

export type getMeResponse401 = {
  data: GetMe401;
  status: 401;
};

export type getMeResponse500 = {
  data: GetMe500;
  status: 500;
};

export type getMeResponseSuccess = getMeResponse200 & {
  headers: Headers;
};
export type getMeResponseError = (getMeResponse401 | getMeResponse500) & {
  headers: Headers;
};

export type getMeResponse = getMeResponseSuccess | getMeResponseError;

export const getGetMeUrl = () => {
  return `/me/`;
};

export const getMe = async (options?: RequestInit): Promise<getMeResponse> => {
  return customFetch<getMeResponse>(getGetMeUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary List all available reasons for procrastination
 */
export type listReasonsForProcrastinationResponse200 = {
  data: ListReasonsForProcrastination200Item[];
  status: 200;
};

export type listReasonsForProcrastinationResponse401 = {
  data: ListReasonsForProcrastination401;
  status: 401;
};

export type listReasonsForProcrastinationResponse500 = {
  data: ListReasonsForProcrastination500;
  status: 500;
};

export type listReasonsForProcrastinationResponseSuccess =
  listReasonsForProcrastinationResponse200 & {
    headers: Headers;
  };
export type listReasonsForProcrastinationResponseError = (
  | listReasonsForProcrastinationResponse401
  | listReasonsForProcrastinationResponse500
) & {
  headers: Headers;
};

export type listReasonsForProcrastinationResponse =
  | listReasonsForProcrastinationResponseSuccess
  | listReasonsForProcrastinationResponseError;

export const getListReasonsForProcrastinationUrl = () => {
  return `/reasons-for-procrastination/`;
};

export const listReasonsForProcrastination = async (
  options?: RequestInit,
): Promise<listReasonsForProcrastinationResponse> => {
  return customFetch<listReasonsForProcrastinationResponse>(
    getListReasonsForProcrastinationUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Hello, World
 */
export type getResponse200 = {
  data: Get200;
  status: 200;
};

export type getResponseSuccess = getResponse200 & {
  headers: Headers;
};
export type getResponse = getResponseSuccess;

export const getGetUrl = () => {
  return `/`;
};

export const get = async (options?: RequestInit): Promise<getResponse> => {
  return customFetch<getResponse>(getGetUrl(), {
    ...options,
    method: "GET",
  });
};
